export const INSPIRATIONAL_QUOTES = [
  { quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", footer: "Take a deep breath." },
  { quote: "Believe you can and you're halfway there.", footer: "Your mindset is your greatest asset." },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", footer: "Keep moving forward." },
  { quote: "It always seems impossible until it's done.", footer: "Nelson Mandela" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", footer: "C.S. Lewis" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", footer: "Steve Jobs" },
  { quote: "The only way to do great work is to love what you do.", footer: "Stay passionate." },
  { quote: "Every morning we are born again. What we do today is what matters most.", footer: "Buddha" },
  { quote: "Do what you can, with what you have, where you are.", footer: "Theodore Roosevelt" },
  { quote: "Everything you've ever wanted is on the other side of fear.", footer: "George Addair" },
  { quote: "Dream big and dare to fail.", footer: "Norman Vaughan" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", footer: "Zig Ziglar" },
  { quote: "If you're going through hell, keep going.", footer: "Winston Churchill" },
  { quote: "It is during our darkest moments that we must focus to see the light.", footer: "Aristotle" },
  { quote: "The best way to predict your future is to create it.", footer: "Abraham Lincoln" },
  { quote: "Happiness is not something readymade. It comes from your own actions.", footer: "Dalai Lama" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", footer: "Confucius" },
  { quote: "You must be the change you wish to see in the world.", footer: "Mahatma Gandhi" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", footer: "Franklin D. Roosevelt" },
  { quote: "The willpower to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", footer: "Confucius" },
  { quote: "Innovation distinguishes between a leader and a follower.", footer: "Steve Jobs" },
  { quote: "The secret of getting ahead is getting started.", footer: "Mark Twain" },
  { quote: "The only person you are destined to become is the person you decide to be.", footer: "Ralph Waldo Emerson" },
  { quote: "If you can dream it, you can do it.", footer: "Walt Disney" },
  { quote: "Action is the foundational key to all success.", footer: "Pablo Picasso" },
  { quote: "Don't judge each day by the harvest you reap but by the seeds that you plant.", footer: "Robert Louis Stevenson" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", footer: "Eleanor Roosevelt" },
  { quote: "Always remember that you are absolutely unique. Just like everyone else.", footer: "Margaret Mead" },
  { quote: "Don't let yesterday take up too much of today.", footer: "Will Rogers" },
  { quote: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", footer: "Unknown" },
  { quote: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", footer: "Steve Jobs" },
  { quote: "People who are crazy enough to think they can change the world, are the ones who do.", footer: "Rob Siltanen" },
  { quote: "We may encounter many defeats but we must not be defeated.", footer: "Maya Angelou" },
  { quote: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", footer: "Johann Wolfgang von Goethe" },
  { quote: "Imagine your life is perfect in every respect; what would it look like?", footer: "Brian Tracy" },
  { quote: "We generate fears while we sit. We overcome them by action.", footer: "Dr. Henry Link" },
  { quote: "Whether you think you can or think you can't, you're right.", footer: "Henry Ford" },
  { quote: "Security is mostly a superstition. Life is either a daring adventure or nothing.", footer: "Helen Keller" },
  { quote: "The man who has confidence in himself gains the confidence of others.", footer: "Hasidic Proverb" },
  { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", footer: "Jordan Belfort" },
  { quote: "Integrity is the most valuable and respected quality of leadership. Always keep your word.", footer: "Brian Tracy" },
  { quote: "Leaders set high standards. Refuse to tolerate mediocrity or poor performance.", footer: "Brian Tracy" },
  { quote: "Clarity is the key to effective leadership. What are your goals?", footer: "Brian Tracy" },
  { quote: "The best leaders are those most interested in surrounding themselves with assistants and associates smarter than they are.", footer: "John C. Maxwell" },
  { quote: "A leader is one who knows the way, goes the way, and shows the way.", footer: "John C. Maxwell" },
  { quote: "Leadership is not about titles, positions, or flowcharts. It is about one life influencing another.", footer: "John C. Maxwell" },
  { quote: "A great leader's courage to fulfill his vision comes from passion, not position.", footer: "John C. Maxwell" },
  { quote: "The growth and development of people is the highest calling of leadership.", footer: "John C. Maxwell" },
  { quote: "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.", footer: "John Quincy Adams" },
  { quote: "Leadership and learning are indispensable to each other.", footer: "John F. Kennedy" },
  { quote: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", footer: "Ronald Reagan" },
  { quote: "Example is not the main thing in influencing others. It is the only thing.", footer: "Albert Schweitzer" },
  { quote: "The standard of excellence is not a destination, it's a journey.", footer: "Keep striving." },
  { quote: "Success usually comes to those who are too busy to be looking for it.", footer: "Henry David Thoreau" },
  { quote: "Opportunities don't happen. You create them.", footer: "Chris Grosser" },
  { quote: "Don't be afraid to give up the good to go for the great.", footer: "John D. Rockefeller" },
  { quote: "I find that the harder I work, the more luck I seem to have.", footer: "Thomas Jefferson" },
  { quote: "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.", footer: "Ray Goforth" },
  { quote: "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.", footer: "Jim Rohn" },
  { quote: "Try not to become a man of success. Rather become a man of value.", footer: "Albert Einstein" },
  { quote: "Stop chasing the money and start chasing the passion.", footer: "Tony Hsieh" },
  { quote: "Success is walking from failure to failure with no loss of enthusiasm.", footer: "Winston Churchill" },
  { quote: "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.", footer: "G.K. Chesterton" },
  { quote: "Would you like me to give you a formula for success? It's quite simple, really: Double your rate of failure.", footer: "Thomas J. Watson" },
  { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", footer: "Jim Rohn" },
  { quote: "The ones who are crazy enough to think they can change the world are the ones who do.", footer: "Steve Jobs" },
  { quote: "Do one thing every day that scares you.", footer: "Eleanor Roosevelt" },
  { quote: "All our dreams can come true if we have the courage to pursue them.", footer: "Walt Disney" },
  { quote: "Good things come to people who wait, but better things come to those who go out and get them.", footer: "Anonymous" },
  { quote: "If you do what you always did, you will get what you always got.", footer: "Anonymous" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", footer: "Robert Collier" },
  { quote: "If you want to achieve excellence, you can get there today. As of this second, stop doing less-than-excellent work.", footer: "Thomas J. Watson" },
  { quote: "All progress takes place outside the comfort zone.", footer: "Michael John Bobak" },
  { quote: "You may have to fight a battle more than once to win it.", footer: "Margaret Thatcher" },
  { quote: "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", footer: "David Brinkley" },
  { quote: "The road to success and the road to failure are almost exactly the same.", footer: "Colin R. Davis" },
  { quote: "I never dreamed about success. I worked for it.", footer: "Estee Lauder" },
  { quote: "The only place where success comes before work is in the dictionary.", footer: "Vidal Sassoon" },
  { quote: "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.", footer: "Zig Ziglar" },
  { quote: "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it.", footer: "Charles F. Kettering" },
  { quote: "The secret of success is to do the common thing uncommonly well.", footer: "John D. Rockefeller Jr." },
  { quote: "Success is not just about what you accomplish in your life; it's about what you inspire others to do.", footer: "Unknown" },
  { quote: "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.", footer: "Booker T. Washington" },
  { quote: "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", footer: "Theodore N. Vail" },
  { quote: "Don't let the fear of losing be greater than the excitement of winning.", footer: "Robert Kiyosaki" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", footer: "Franklin D. Roosevelt" },
  { quote: "Don't wait. The time will never be just right.", footer: "Napoleon Hill" },
  { quote: "The way to get started is to quit talking and begin doing.", footer: "Walt Disney" },
  { quote: "Setting goals is the first step in turning the invisible into the visible.", footer: "Tony Robbins" },
  { quote: "Your goals are the road maps that guide you and show you what is possible for your life.", footer: "Les Brown" },
  { quote: "The power of imagination makes us infinite.", footer: "John Muir" },
  { quote: "When you have a dream, you've got to grab it and never let go.", footer: "Carol Burnett" },
  { quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", footer: "Jimmy Dean" },
  { quote: "No matter what you're going through, there's a light at the end of the tunnel.", footer: "Demi Lovato" },
  { quote: "Perfection is not attainable, but if we chase perfection we can catch excellence.", footer: "Vince Lombardi" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", footer: "Charles R. Swindoll" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", footer: "Walt Whitman" },
  { quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", footer: "Helen Keller" },
  { quote: "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.", footer: "Norman Vincent Peale" },
  { quote: "If you can dream it, you can do it.", footer: "Walt Disney" },
  { quote: "Start where you are. Use what you have. Do what you can.", footer: "Arthur Ashe" },
  { quote: "The only way to do great work is to love what you do.", footer: "Steve Jobs" },
  { quote: "With the new day comes new strength and new thoughts.", footer: "Eleanor Roosevelt" },
  { quote: "The optimist sees the rose and not its thorns; the pessimist stares at the thorns, oblivious of the rose.", footer: "Kahlil Gibran" },
  { quote: "Don't watch the clock; do what it does. Keep going.", footer: "Sam Levenson" },
  { quote: "You are never too old to set another goal or to dream a new dream.", footer: "C.S. Lewis" },
  { quote: "Aim for the moon. If you miss, you may hit a star.", footer: "W. Clement Stone" },
  { quote: "Problems are not stop signs, they are guidelines.", footer: "Robert H. Schuller" },
  { quote: "You must do the things you think you cannot do.", footer: "Eleanor Roosevelt" },
  { quote: "Opportunities don't happen, you create them.", footer: "Chris Grosser" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", footer: "Winston Churchill" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", footer: "C.S. Lewis" },
  { quote: "Believe you can and you're halfway there.", footer: "Theodore Roosevelt" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", footer: "Franklin D. Roosevelt" },
  { quote: "Dream big and dare to fail.", footer: "Norman Vaughan" },
  { quote: "It is never too late to be what you might have been.", footer: "George Eliot" },
  { quote: "Action is the foundational key to all success.", footer: "Pablo Picasso" },
  { quote: "Everything you've ever wanted is on the other side of fear.", footer: "George Addair" },
  { quote: "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.", footer: "Confucius" },
  { quote: "Happiness is not by chance, but by choice.", footer: "Jim Rohn" },
  { quote: "Keep your eyes on the stars, and your feet on the ground.", footer: "Theodore Roosevelt" },
  { quote: "Don't let what you cannot do interfere with what you can do.", footer: "John Wooden" },
  { quote: "Positive anything is better than negative nothing.", footer: "Elbert Hubbard" },
  { quote: "The only person you are destined to become is the person you decide to be.", footer: "Ralph Waldo Emerson" },
  { quote: "Make each day your masterpiece.", footer: "John Wooden" },
  { quote: "It always seems impossible until it's done.", footer: "Nelson Mandela" },
  { quote: "Someday is not a day of the week.", footer: "Denise Brennan-Nelson" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", footer: "Mahatma Gandhi" },
  { quote: "The best way to predict your future is to create it.", footer: "Abraham Lincoln" },
  { quote: "We become what we think about.", footer: "Earl Nightingale" },
  { quote: "The future belongs to those who learn more skills and combine them in creative ways.", footer: "Robert Greene" },
  { quote: "Success is how high you bounce when you hit bottom.", footer: "George S. Patton" },
  { quote: "If you want to lift yourself up, lift up someone else.", footer: "Booker T. Washington" },
  { quote: "Courage is grace under pressure.", footer: "Ernest Hemingway" },
  { quote: "Don't be afraid to give up the good to go for the great.", footer: "John D. Rockefeller" },
  { quote: "A person who never made a mistake never tried anything new.", footer: "Albert Einstein" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", footer: "Eleanor Roosevelt" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", footer: "Thomas A. Edison" },
  { quote: "Life is what happens when you're busy making other plans.", footer: "John Lennon" },
  { quote: "Get busy living or get busy dying.", footer: "Stephen King" },
  { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", footer: "Amelia Earhart" },
  { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", footer: "Mother Teresa" },
  { quote: "The purpose of our lives is to be happy.", footer: "Dalai Lama" },
  { quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", footer: "Joshua J. Marine" },
  { quote: "I attribute my success to this: I never gave or took any excuse.", footer: "Florence Nightingale" },
  { quote: "You miss 100% of the shots you don't take.", footer: "Wayne Gretzky" },
  { quote: "Whether you think you can or you think you can't, you're right.", footer: "Henry Ford" },
  { quote: "The only limit to your impact is your imagination and commitment.", footer: "Tony Robbins" },
  { quote: "Life is not about finding yourself. Life is about creating yourself.", footer: "George Bernard Shaw" },
  { quote: "In the middle of every difficulty lies opportunity.", footer: "Albert Einstein" },
  { quote: "Fall seven times and stand up eight.", footer: "Japanese Proverb" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", footer: "Chinese Proverb" },
  { quote: "Your time is limited, don't waste it living someone else's life.", footer: "Steve Jobs" },
  { quote: "Everything has beauty, but not everyone sees it.", footer: "Confucius" },
  { quote: "Eighty percent of success is showing up.", footer: "Woody Allen" },
  { quote: "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", footer: "Oprah Winfrey" },
  { quote: "Remember that no one can make you feel inferior without your consent.", footer: "Eleanor Roosevelt" },
  { quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", footer: "Jimmy Dean" },
  { quote: "Nothing is impossible, the word itself says 'I'm possible'!", footer: "Audrey Hepburn" },
  { quote: "The only way to do great work is to love what you do.", footer: "Steve Jobs" }
];
