/* ═══════════════════════════════════════════════════════════════════════════════
   BWF WELLBEING — DAILY CHALLENGES BANK
   40 challenges so every day feels fresh. Rotated deterministically by day-of-year.
   Each category maps to an icon + colour theme used in WellBeingPage.tsx.
   ═══════════════════════════════════════════════════════════════════════════════ */

export type ChallengeCategory = "health" | "mindfulness" | "wellness" | "social" | "creative";

export interface DailyChallenge {
  id: number;
  title: string;
  emoji: string;
  description: string;
  instruction: string;
  color: string;
  bg: string;
  category: ChallengeCategory;
}

export const CHALLENGES: DailyChallenge[] = [
  /* ── HEALTH ───────────────────────────────────────────────────────────────── */
  {
    id: 1,
    title: "Hydration Hero",
    emoji: "💧",
    description: "Drink 8 glasses of water today",
    instruction: "Fill a big bottle right now and sip throughout the day!",
    color: "#06b6d4",
    bg: "#cffafe",
    category: "health",
  },
  {
    id: 2,
    title: "Power Breakfast",
    emoji: "🥑",
    description: "Eat a nutritious breakfast this morning",
    instruction: "No skipping! Even a banana and milk counts. Fuel your brain.",
    color: "#16a34a",
    bg: "#dcfce7",
    category: "health",
  },
  {
    id: 3,
    title: "Step Up",
    emoji: "🚶",
    description: "Take a 10-minute walk outside",
    instruction: "Leave your phone behind for 10 minutes and just walk and notice things.",
    color: "#2563eb",
    bg: "#dbeafe",
    category: "health",
  },
  {
    id: 4,
    title: "Screen Break",
    emoji: "👁️",
    description: "Take a 20-20-20 eye break every hour",
    instruction: "Every hour, look at something 20 feet away for 20 seconds. Set a timer!",
    color: "#7c3aed",
    bg: "#ede9fe",
    category: "health",
  },
  {
    id: 5,
    title: "Early Bird",
    emoji: "🌅",
    description: "Wake up 15 minutes earlier than usual",
    instruction: "Use those 15 minutes to stretch, breathe, or just sit in quiet.",
    color: "#d97706",
    bg: "#fef3c7",
    category: "health",
  },
  {
    id: 6,
    title: "Veggie Boost",
    emoji: "🥦",
    description: "Eat at least one vegetable today",
    instruction: "Add a salad, snack on a carrot, or have some sabzi with roti. Easy win!",
    color: "#059669",
    bg: "#d1fae5",
    category: "health",
  },
  {
    id: 7,
    title: "Posture Check",
    emoji: "🧍",
    description: "Sit up straight for the next 30 minutes",
    instruction: "Uncross your legs, relax your shoulders, chin up. Set a timer.",
    color: "#0891b2",
    bg: "#cffafe",
    category: "health",
  },
  {
    id: 8,
    title: "Sleep Prep",
    emoji: "🌙",
    description: "Put your phone away 30 mins before bed",
    instruction: "Tonight, swap screens for a book, journaling, or just calm breathing.",
    color: "#4f46e5",
    bg: "#e0e7ff",
    category: "health",
  },

  /* ── MINDFULNESS ─────────────────────────────────────────────────────────── */
  {
    id: 9,
    title: "Grateful Heart",
    emoji: "🙏",
    description: "Write 3 things you're grateful for",
    instruction: "Even tiny things count — a warm meal, a good laugh, sunshine.",
    color: "#f59e0b",
    bg: "#fef3c7",
    category: "mindfulness",
  },
  {
    id: 10,
    title: "Deep Breath",
    emoji: "🌬️",
    description: "Do a 4-4-4 box breathing exercise",
    instruction: "Inhale for 4, hold for 4, exhale for 4. Do 5 rounds right now.",
    color: "#3b82f6",
    bg: "#dbeafe",
    category: "mindfulness",
  },
  {
    id: 11,
    title: "5-Sense Scan",
    emoji: "🌿",
    description: "Ground yourself with the 5-4-3-2-1 technique",
    instruction: "Name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste.",
    color: "#10b981",
    bg: "#d1fae5",
    category: "mindfulness",
  },
  {
    id: 12,
    title: "Mindful Meal",
    emoji: "🍽️",
    description: "Eat one meal without your phone today",
    instruction: "Just taste your food. No reels. Notice the flavours, the texture, the warmth.",
    color: "#ea580c",
    bg: "#ffedd5",
    category: "mindfulness",
  },
  {
    id: 13,
    title: "Emotion Check",
    emoji: "💭",
    description: "Name exactly what you're feeling right now",
    instruction: "'Fine' doesn't count. Is it anxious? Bored? Lonely? Naming it reduces it.",
    color: "#9333ea",
    bg: "#f3e8ff",
    category: "mindfulness",
  },
  {
    id: 14,
    title: "Nature Moment",
    emoji: "☁️",
    description: "Spend 5 minutes watching the sky or plants",
    instruction: "Step outside. Watch clouds drift or leaves move. Just observe without scrolling.",
    color: "#0284c7",
    bg: "#e0f2fe",
    category: "mindfulness",
  },
  {
    id: 15,
    title: "Body Scan",
    emoji: "🧘",
    description: "Do a 3-minute body scan meditation",
    instruction: "Start at your feet and slowly notice each body part. Release tension as you go.",
    color: "#be185d",
    bg: "#fce7f3",
    category: "mindfulness",
  },
  {
    id: 16,
    title: "Slow Down",
    emoji: "⏳",
    description: "Do one thing today at half your normal speed",
    instruction: "Brush your teeth slowly. Eat slowly. Walk slowly. Notice what you usually miss.",
    color: "#b45309",
    bg: "#fef3c7",
    category: "mindfulness",
  },
  {
    id: 17,
    title: "Worry Jar",
    emoji: "📝",
    description: "Write your worries down and close the book",
    instruction: "Spend 5 minutes writing everything worrying you, then close the notebook. Done.",
    color: "#6d28d9",
    bg: "#ede9fe",
    category: "mindfulness",
  },

  /* ── WELLNESS ────────────────────────────────────────────────────────────── */
  {
    id: 18,
    title: "Move & Groove",
    emoji: "🎵",
    description: "Dance or stretch for 5 minutes",
    instruction: "Put on your absolute favourite song and just move. No one is watching!",
    color: "#ec4899",
    bg: "#fce7f3",
    category: "wellness",
  },
  {
    id: 19,
    title: "Laugh Out Loud",
    emoji: "😂",
    description: "Watch or read something that makes you genuinely laugh",
    instruction: "Find a meme, a clip, a memory. Real laughter is medicine.",
    color: "#f97316",
    bg: "#ffedd5",
    category: "wellness",
  },
  {
    id: 20,
    title: "Power Stretch",
    emoji: "🤸",
    description: "Do 5 minutes of full-body stretching",
    instruction: "Neck rolls, shoulder shrugs, forward fold, quad stretch. Your body will thank you.",
    color: "#dc2626",
    bg: "#fee2e2",
    category: "wellness",
  },
  {
    id: 21,
    title: "Comfort Corner",
    emoji: "☕",
    description: "Make yourself a warm drink and enjoy it slowly",
    instruction: "Chai, milk, hot chocolate — whatever is your favourite. No phone while sipping.",
    color: "#92400e",
    bg: "#fef3c7",
    category: "wellness",
  },
  {
    id: 22,
    title: "Tidy Space",
    emoji: "✨",
    description: "Spend 10 minutes tidying your desk or room",
    instruction: "Clutter causes low-key anxiety. A clean space = a calmer mind.",
    color: "#0891b2",
    bg: "#cffafe",
    category: "wellness",
  },
  {
    id: 23,
    title: "Playlist Power",
    emoji: "🎧",
    description: "Build a 'feel-good' playlist of 5 songs",
    instruction: "Intentionally pick 5 songs that make you feel alive, safe, or happy.",
    color: "#7c3aed",
    bg: "#ede9fe",
    category: "wellness",
  },
  {
    id: 24,
    title: "Rest & Recharge",
    emoji: "😴",
    description: "Take a 10-minute rest — no screens, no tasks",
    instruction: "Lie down, close your eyes, do nothing. Rest is not laziness.",
    color: "#4338ca",
    bg: "#e0e7ff",
    category: "wellness",
  },
  {
    id: 25,
    title: "Positive Mirror",
    emoji: "🪞",
    description: "Say one kind thing to yourself in the mirror",
    instruction: "Look yourself in the eye and say it out loud. 'I am enough.' 'I am trying.'",
    color: "#be185d",
    bg: "#fce7f3",
    category: "wellness",
  },

  /* ── SOCIAL ──────────────────────────────────────────────────────────────── */
  {
    id: 26,
    title: "Kind Heart",
    emoji: "💝",
    description: "Do something kind for someone today",
    instruction: "Smile, hold a door, say thank you, help a classmate. Small acts matter.",
    color: "#8b5cf6",
    bg: "#ede9fe",
    category: "social",
  },
  {
    id: 27,
    title: "Check In",
    emoji: "📞",
    description: "Call or message a friend or family member",
    instruction: "Someone who matters to you. Just 'hey, I was thinking of you' is enough.",
    color: "#16a34a",
    bg: "#dcfce7",
    category: "social",
  },
  {
    id: 28,
    title: "Active Listen",
    emoji: "👂",
    description: "Have a conversation where you only listen",
    instruction: "Let a friend or family member speak. No interrupting. No advice. Just listen.",
    color: "#0369a1",
    bg: "#e0f2fe",
    category: "social",
  },
  {
    id: 29,
    title: "Compliment Drop",
    emoji: "⭐",
    description: "Give 3 genuine compliments today",
    instruction: "One to a friend, one to a teacher or elder, one to a stranger if you can!",
    color: "#d97706",
    bg: "#fef3c7",
    category: "social",
  },
  {
    id: 30,
    title: "Forgive Forward",
    emoji: "🕊️",
    description: "Let go of one small grudge or annoyance",
    instruction: "Think of something small bothering you. Choose to let it go. Not for them — for you.",
    color: "#6d28d9",
    bg: "#ede9fe",
    category: "social",
  },
  {
    id: 31,
    title: "Thank You Note",
    emoji: "💌",
    description: "Write a thank-you message to someone",
    instruction: "Doesn't need to be fancy. 'Thank you for being there for me' goes a long way.",
    color: "#be185d",
    bg: "#fce7f3",
    category: "social",
  },

  /* ── CREATIVE ─────────────────────────────────────────────────────────────── */
  {
    id: 32,
    title: "Doodle Break",
    emoji: "🎨",
    description: "Doodle freely for 5 minutes",
    instruction: "No artistic talent needed. Scribble shapes, patterns, or whatever. Just flow.",
    color: "#ec4899",
    bg: "#fce7f3",
    category: "creative",
  },
  {
    id: 33,
    title: "Poem a Day",
    emoji: "📜",
    description: "Write a tiny 4-line poem about your day",
    instruction: "It doesn't have to rhyme! Just describe your mood in 4 honest lines.",
    color: "#7c3aed",
    bg: "#f3e8ff",
    category: "creative",
  },
  {
    id: 34,
    title: "Photo Story",
    emoji: "📸",
    description: "Take a photo of something beautiful today",
    instruction: "Light through a window, a flower, your lunch. Notice beauty you usually ignore.",
    color: "#0891b2",
    bg: "#cffafe",
    category: "creative",
  },
  {
    id: 35,
    title: "Dream Journal",
    emoji: "🌙",
    description: "Write down last night's dream or a daydream",
    instruction: "Even fragments count. What was the feeling? The colour? Don't judge it.",
    color: "#4f46e5",
    bg: "#e0e7ff",
    category: "creative",
  },
  {
    id: 36,
    title: "Memory Lane",
    emoji: "📷",
    description: "Look at a happy photo from the past",
    instruction: "Find one memory that made you genuinely smile. Remember how it felt.",
    color: "#d97706",
    bg: "#fef3c7",
    category: "creative",
  },
  {
    id: 37,
    title: "Cook Something",
    emoji: "👨‍🍳",
    description: "Help make or cook something simple today",
    instruction: "Even making tea counts! Creating something with your hands is calming.",
    color: "#ea580c",
    bg: "#ffedd5",
    category: "creative",
  },
  {
    id: 38,
    title: "Vision Board",
    emoji: "🌟",
    description: "Write or draw 3 dreams you have for your future",
    instruction: "Big or small. What do you want to experience? Who do you want to be?",
    color: "#9333ea",
    bg: "#f3e8ff",
    category: "creative",
  },
  {
    id: 39,
    title: "Letter to Self",
    emoji: "✉️",
    description: "Write a letter to yourself 1 year from now",
    instruction: "Tell future-you what today feels like, and what you hope for them.",
    color: "#16a34a",
    bg: "#dcfce7",
    category: "creative",
  },
  {
    id: 40,
    title: "Colour Your Mood",
    emoji: "🖍️",
    description: "Describe your mood using only colours",
    instruction: "Is today cobalt blue? Dusty rose? Muddy grey? Write 3 colours that match your mood.",
    color: "#f43f5e",
    bg: "#ffe4e6",
    category: "creative",
  },
];
